-- BATCH Coffee — initial schema
--
-- Run this once in Supabase Studio → SQL Editor, then we never have to
-- touch it again from the dashboard. Subsequent migrations get their
-- own numbered file.
--
-- Tables created here:
--   * profiles            — extends auth.users with display fields
--   * addresses           — saved delivery destinations per user
--   * orders              — header for a single purchase
--   * order_items         — line items inside an order (1-to-many)
--   * subscriptions       — recurring coffee box for a user (single
--                           active subscription is the common case but
--                           the schema allows many)
--   * subscription_cycles — log of each shipment a subscription has
--                           produced; links back to the order it
--                           generated for traceability
--
-- All tables have Row Level Security enabled. Default deny — users see
-- only their own rows, anon role sees nothing. Service-role bypasses
-- RLS by design and is used by cron jobs / migrations.

-- ---------------------------------------------------------------
-- 1. profiles
-- ---------------------------------------------------------------

create table if not exists public.profiles (
  -- Foreign key to auth.users.id — Supabase Auth owns the source row,
  -- profile lives alongside it 1-to-1. On user delete, profile cascades.
  id uuid primary key references auth.users(id) on delete cascade,
  phone text,
  first_name text,
  last_name text,
  email text,
  newsletter boolean default true not null,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

create index if not exists profiles_phone_idx on public.profiles(phone);

-- ---------------------------------------------------------------
-- 2. addresses
-- ---------------------------------------------------------------

create table if not exists public.addresses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  label text not null check (label in ('Дім', 'Робота', 'Інше')),
  recipient text not null,
  phone text not null,
  city text not null,
  destination text not null,
  is_default boolean default false not null,
  created_at timestamptz default now() not null
);

create index if not exists addresses_user_id_idx on public.addresses(user_id);

-- A user should have at most one default address. Enforce via partial
-- unique index — Postgres allows multiple `is_default = false` rows
-- per user but only one `is_default = true`.
create unique index if not exists addresses_one_default_per_user
  on public.addresses(user_id) where (is_default = true);

-- ---------------------------------------------------------------
-- 3. orders + order_items
-- ---------------------------------------------------------------

create type public.order_status as enum (
  'pending',   -- created, payment not yet completed
  'paid',      -- payment confirmed
  'packing',   -- roastery is packing the box
  'shipped',   -- in the carrier's hands
  'delivered', -- customer has it
  'cancelled'  -- voided by customer or staff
);

create type public.delivery_method as enum (
  'novaposhta-branch',
  'novaposhta-postomat',
  'pickup'
);

create type public.payment_method as enum (
  'card', -- via LiqPay or similar
  'cod'   -- cash / terminal on delivery
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  -- Human-friendly order number (BAT-0142) shown to customer + on emails.
  -- Generated by a trigger so we never collide.
  number text not null unique,
  user_id uuid references public.profiles(id) on delete set null,
  status public.order_status not null default 'pending',
  subtotal integer not null,
  delivery_fee integer not null default 0,
  discount integer not null default 0,
  total integer not null,
  delivery_method public.delivery_method not null,
  delivery_address text not null,
  delivery_city text,
  payment_method public.payment_method not null,
  recipient_first_name text not null,
  recipient_last_name text not null,
  recipient_phone text not null,
  recipient_email text,
  comment text,
  -- Tracking number from Nova Poshta after shipment is created.
  tracking_number text,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

create index if not exists orders_user_id_idx on public.orders(user_id);
create index if not exists orders_status_idx on public.orders(status);
create index if not exists orders_created_at_idx on public.orders(created_at desc);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  -- Snapshot of the product at purchase time. If the product is later
  -- renamed or its price changes, the line stays correct historically.
  product_slug text not null,
  product_name text not null,
  thumb text,
  weight_label text not null,
  weight_grams integer not null,
  roast text,
  grind text,
  unit_price integer not null,
  quantity integer not null check (quantity > 0),
  line_total integer not null,
  created_at timestamptz default now() not null
);

create index if not exists order_items_order_id_idx on public.order_items(order_id);

-- ---------------------------------------------------------------
-- Auto-generate human-readable order number: BAT-NNNN, zero-padded
-- to 4 digits. Sequence-backed so two simultaneous orders don't
-- collide. Resets are intentional only.
-- ---------------------------------------------------------------

create sequence if not exists public.order_number_seq start 1000;

create or replace function public.set_order_number()
returns trigger language plpgsql as $$
begin
  if new.number is null then
    new.number := 'BAT-' ||
      lpad(nextval('public.order_number_seq')::text, 4, '0');
  end if;
  return new;
end;
$$;

drop trigger if exists set_order_number on public.orders;
create trigger set_order_number
  before insert on public.orders
  for each row execute function public.set_order_number();

-- ---------------------------------------------------------------
-- 4. subscriptions + cycles
-- ---------------------------------------------------------------

create type public.subscription_status as enum (
  'active',
  'paused',
  'cancelled'
);

create table if not exists public.subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  product_slug text not null,
  product_name text not null,
  thumb text,
  weight_label text not null,
  weight_grams integer not null,
  roast text,
  -- Number of packs shipped each cycle.
  quantity integer not null check (quantity > 0),
  interval_days integer not null check (interval_days >= 7),
  price_per_cycle integer not null,
  -- Next time the cron job should charge + ship this subscription.
  next_date timestamptz not null,
  status public.subscription_status not null default 'active',
  -- LiqPay (or other provider) recurring token. Set after the first
  -- successful authorisation; never null on an active subscription.
  payment_token text,
  cycles_shipped integer not null default 0,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

create index if not exists subscriptions_user_id_idx on public.subscriptions(user_id);
create index if not exists subscriptions_status_idx on public.subscriptions(status);
create index if not exists subscriptions_next_date_idx
  on public.subscriptions(next_date) where status = 'active';

create table if not exists public.subscription_cycles (
  id uuid primary key default gen_random_uuid(),
  subscription_id uuid not null references public.subscriptions(id) on delete cascade,
  -- The order generated for this cycle. Null while pending charge.
  order_id uuid references public.orders(id) on delete set null,
  charged_at timestamptz default now() not null,
  amount integer not null
);

create index if not exists subscription_cycles_subscription_id_idx
  on public.subscription_cycles(subscription_id);

-- ---------------------------------------------------------------
-- 5. updated_at triggers — auto-bump on UPDATE
-- ---------------------------------------------------------------

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists profiles_touch on public.profiles;
create trigger profiles_touch
  before update on public.profiles
  for each row execute function public.touch_updated_at();

drop trigger if exists orders_touch on public.orders;
create trigger orders_touch
  before update on public.orders
  for each row execute function public.touch_updated_at();

drop trigger if exists subscriptions_touch on public.subscriptions;
create trigger subscriptions_touch
  before update on public.subscriptions
  for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------
-- 6. Row Level Security — default deny, explicit per-row allows
-- ---------------------------------------------------------------

alter table public.profiles            enable row level security;
alter table public.addresses           enable row level security;
alter table public.orders              enable row level security;
alter table public.order_items         enable row level security;
alter table public.subscriptions       enable row level security;
alter table public.subscription_cycles enable row level security;

-- profiles: a user can read + update their own profile only.
create policy "profiles: read own"  on public.profiles
  for select using (auth.uid() = id);
create policy "profiles: insert own" on public.profiles
  for insert with check (auth.uid() = id);
create policy "profiles: update own" on public.profiles
  for update using (auth.uid() = id);

-- addresses: full CRUD on own rows.
create policy "addresses: read own"   on public.addresses
  for select using (auth.uid() = user_id);
create policy "addresses: insert own" on public.addresses
  for insert with check (auth.uid() = user_id);
create policy "addresses: update own" on public.addresses
  for update using (auth.uid() = user_id);
create policy "addresses: delete own" on public.addresses
  for delete using (auth.uid() = user_id);

-- orders: customer sees their own. Inserts allowed for own user_id
-- (or anon checkout — see below). Updates are server-only via service
-- role (so customers can't toggle status to 'paid').
create policy "orders: read own" on public.orders
  for select using (auth.uid() = user_id);
create policy "orders: insert own" on public.orders
  for insert with check (
    -- Logged-in customer placing their own order
    (auth.uid() = user_id)
    -- OR guest checkout: user_id is null and so is auth.uid().
    -- We'll tighten this later when we add fraud checks.
    or (user_id is null and auth.uid() is null)
  );

-- order_items: visible iff the parent order is visible to me.
create policy "order_items: read via order" on public.order_items
  for select using (
    exists (
      select 1 from public.orders o
      where o.id = order_items.order_id
        and (o.user_id = auth.uid() or (o.user_id is null and auth.uid() is null))
    )
  );
create policy "order_items: insert via order" on public.order_items
  for insert with check (
    exists (
      select 1 from public.orders o
      where o.id = order_items.order_id
        and (o.user_id = auth.uid() or (o.user_id is null and auth.uid() is null))
    )
  );

-- subscriptions: customer-managed.
create policy "subscriptions: read own" on public.subscriptions
  for select using (auth.uid() = user_id);
create policy "subscriptions: insert own" on public.subscriptions
  for insert with check (auth.uid() = user_id);
create policy "subscriptions: update own" on public.subscriptions
  for update using (auth.uid() = user_id);
create policy "subscriptions: delete own" on public.subscriptions
  for delete using (auth.uid() = user_id);

-- subscription_cycles: visible iff the parent subscription is mine.
-- Inserts are server-only (cron job uses service role) so customers
-- can't fake billing history.
create policy "subscription_cycles: read via subscription"
  on public.subscription_cycles
  for select using (
    exists (
      select 1 from public.subscriptions s
      where s.id = subscription_cycles.subscription_id
        and s.user_id = auth.uid()
    )
  );

-- ---------------------------------------------------------------
-- 7. Auto-create profile on signup
-- ---------------------------------------------------------------
-- When Supabase Auth inserts into auth.users (signUp / verifyOtp), we
-- mirror a row into public.profiles so the rest of the app can rely
-- on it always existing.

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, phone, email)
  values (new.id, new.phone, new.email)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();
